accounts/urls.py
from django.urls import path
from .views import (
    user_login,
    user_logout,
    user_signup,
    view_my_profile,
    view_user_profile,
    edit_user_profile,
)

urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("signup/", user_signup, name="signup"),
    path("user-profile/mine/", view_my_profile, name="view_my_profile"),
    path("user-profile/<int:id>/", view_user_profile, name="view_user_profile"),
    path("user-profile/edit/", edit_user_profile, name="edit_user_profile"),
]

tasks/urls.py
from django.urls import path
from .views import create_task, list_tasks, delete_task, edit_task

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", list_tasks, name="show_my_tasks"),
    path("<int:id>/delete/", delete_task, name="delete_task"),
    path("<int:id>/edit/", edit_task, name="edit_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static


def redirect_to_home(request):
    return redirect("list_all_projects")


urlpatterns = [
    path("", redirect_to_home, name="home"),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


LEVEL = (
    ("team", "team leader"),
    ("member", "team member"),
)


class Team(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    picture = models.ImageField(
        upload_to="images/team",
        null=True,
        default=None,
    )

    def __str__(self):
        return self.name


class UserProfileManager(models.Manager):
    pass


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(
        upload_to="images/profile",
        null=True,
        default=None,
    )
    team = models.ForeignKey(
        Team,
        related_name="members",
        on_delete=models.PROTECT,
        null=True,
    )
    level = models.CharField(
        choices=LEVEL,
        max_length=150,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.user.username

    def createProfile(sender, **kwargs):
        if kwargs['created']:
            user_profile = UserProfile.objects.create(user=kwargs['instance'])

    post_save.connect(createProfile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )


class SignUpForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        error_messages={
            "unique": ("This username is already taken")
        }
    )
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )
    password_confirmation = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    email = forms.EmailField(
        max_length=150,
        error_messages={
            "unique": ("This email has already been registered")
        }
    )


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)

        self.fields["level"].choices = (
            ('team', 'team leader'),
            ('member', 'team member')
        )

    class Meta:
        model = UserProfile
        exclude = (
            "user",
        )
        widgets = {
            "picture": forms.FileInput(attrs={'class':'form-control'}),
            "team": forms.Select(attrs={'class':'form-select'}),
            "level": forms.Select(attrs={'class':'form-select'}),
        }


class EditUserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
        )
        widgets = {
            "username": forms.TextInput(attrs={'class':'form-control'}),
            "first_name": forms.TextInput(attrs={'class':'form-control'}),
            "last_name": forms.TextInput(attrs={'class':'form-control'}),
            "email": forms.EmailInput(attrs={'class':'form-control'}),
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.template.context_processors import csrf
from django.contrib.auth.models import User
from .models import UserProfile, Team
from .forms import LoginForm, SignUpForm, UserProfileForm, EditUserProfileForm


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
            else:
                form.add_error("password", "The password is incorrect")
                form.add_error("username", "The username does not exist")
    else:
        form = LoginForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def user_logout(request):
    logout(request)
    return redirect("login")


def user_signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            email = form.cleaned_data["email"]
            if User.objects.filter(username=form.cleaned_data["username"]).exists():
                form.add_error("username", "This username is already taken")
            elif User.objects.filter(email=form.cleaned_data["email"]).exists():
                form.add_error("email", "This email has already been registered")
            elif password == password_confirmation:
                user = User.objects.create_user(
                    username,
                    password=password,
                    email=email,
                    first_name=first_name,
                    last_name=last_name,
                )
                login(request, user)
                return redirect("home")
            else:
                form.add_error("password", "The passwords do not match")
    else:
        form = SignUpForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


@login_required
def view_my_profile(request):
    return render(request, "accounts/user-profile/mine.html")


@login_required
def view_user_profile(request, id):
    profile = get_object_or_404(UserProfile, id=id)
    context = {
        "profile": profile,
    }
    return render(request, "accounts/user-profile/view.html", context)


@login_required
def edit_user_profile(request):
    if request.method == "POST":
        uform = EditUserProfileForm(request.POST, instance=request.user)
        pform = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if uform.is_valid() and pform.is_valid():
            user_form = uform.save()
            profile = pform.save(False)
            profile.user = user_form
            profile.save()
            return redirect("view_my_profile")
        else:
            uform.add_error("password", "The passwords do not match")
    else:
        uform = EditUserProfileForm(instance=request.user)
        try:
            pform = UserProfileForm(instance=request.user.userprofile)
        except UserProfile.DoesNotExist:
            pform = UserProfileForm()
    args = {}
    args.update(csrf(request))
    args['uform'] = uform
    args['pform'] = pform
    return render(request, "accounts/user-profile/edit.html", args)

accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static "css/sign-in-or-up.css" %}">
    </head>
    <body>
        <header class="text-light pt-5 pb-5 mb-4 px-5 pg-lg-0 pt-lg-5 text-center"
                style="background-color: rgb(74, 44, 95)">
            <div class="container">
                <h1>
                    pr <i class="bi bi-check-circle text-warning"></i> ma
                </h1>
                <p>
                    Don't have an account? <a href="{% url "signup" %}">Sign up</a>
                </p>
            </div>
        </header>
        <section class="text-center">
            <div class="container">
                <div class="row align-items-center text-center justify-content-center py-5">
                    <div class="card position-absolute mt-5 py-2 shadow-sm"
                         style="width: 500px">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {% if form.errors %}<span class="text-muted">The login is incorrect. Please try again.</span>{% endif %}
                                <div>
                                    <label for="id_username"></label>
                                    <input type="text"
                                           name="username"
                                           maxlength="150"
                                           required=""
                                           id="id_username"
                                           placeholder="Username"
                                           class="form-control">
                                </div>
                                <div>
                                    <label for="id_password"></label>
                                    <input type="password"
                                           name="password"
                                           maxlength="150"
                                           required=""
                                           id="id_password"
                                           placeholder="Password"
                                           class="form-control">
                                </div>
                                <div class="d-grid mt-4 mb-3">
                                    <button class="btn text-white">Login</button>
                                </div>
                            </form>
                            <div>
                                <a href="#" class="purple-link">Forgot username?</a>
                                <span><i class="bi bi-dot"></i></span>
                                <a href="#" class="purple-link">Forgot password?</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

accounts/templates/accounts/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sign Up</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static "css/sign-in-or-up.css" %}">
    </head>
    <body>
        <header class="text-light py-5 mb-5 px-5 pg-lg-0 pt-lg-5 text-center"
                style="background-color: rgb(74, 44, 95)">
            <div class="container">
                <h1>Sign Up</h1>
                <p>
                    Already have an account? <a href="{% url "login" %}">Login</a>
                </p>
            </div>
        </header>
        <section class="text-center">
            <div class="container">
                <div class="row align-items-center text-start justify-content-center mb-5 pb-5">
                    <div class="card position-absolute py-3 shadow-sm"
                         style="width: 500px;
                                margin-top: 490px">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {% if form.errors %}
                                    <div class="text-muted text-center mb-2">
                                        <strong>Holy guacamole!</strong>
                                        {% if form.username.errors %}This username is already taken.{% endif %}
                                        {% if form.password.errors %}The passwords do not match.{% endif %}
                                        {% if form.email.errors %}This email has already been registered.{% endif %}
                                    </div>
                                {% endif %}
                                <div>
                                    <label for="id_username" class="form-label">
                                        <span class="text-danger">*</span> Username:
                                    </label>
                                    <input type="text"
                                           name="username"
                                           maxlength="150"
                                           required=""
                                           id="id_username"
                                           placeholder="Username"
                                           class="form-control mb-3">
                                </div>
                                <div>
                                    <label for="id_password" class="form-label">
                                        <span class="text-danger">*</span> Password:
                                    </label>
                                    <input type="password"
                                           name="password"
                                           maxlength="150"
                                           required=""
                                           id="id_password"
                                           placeholder="Password"
                                           class="form-control mb-3">
                                </div>
                                <div>
                                    <label for="id_password_confirmation" class="form-label">
                                        <span class="text-danger">*</span> Password confirmation:
                                    </label>
                                    <input type="password"
                                           name="password_confirmation"
                                           maxlength="150"
                                           required=""
                                           id="id_password_confirmation"
                                           placeholder="Confirm password"
                                           class="form-control mb-3">
                                </div>
                                <div>
                                    <label for="id_first_name" class="form-label">
                                        <span class="text-danger">*</span> First name:
                                    </label>
                                    <input type="text"
                                           name="first_name"
                                           maxlength="150"
                                           required=""
                                           id="id_first_name"
                                           placeholder="First name"
                                           class="form-control mb-3">
                                </div>
                                <div>
                                    <label for="id_last_name" class="form-label">
                                        <span class="text-danger">*</span> Last name:
                                    </label>
                                    <input type="text"
                                           name="last_name"
                                           maxlength="150"
                                           required=""
                                           id="id_last_name"
                                           placeholder="Last name"
                                           class="form-control mb-3">
                                </div>
                                <div>
                                    <label for="id_email" class="form-label">
                                        <span class="text-danger">*</span> Email:
                                    </label>
                                    <input type="email"
                                           name="email"
                                           maxlength="150"
                                           required=""
                                           id="id_email"
                                           placeholder="Email"
                                           class="form-control mb-3">
                                </div>
                                <div class="d-grid mt-4 mb-2">
                                    <button class="btn text-white">Sign up</button>
                                </div>
                                <span class="text-danger mb-4">*</span> Required field
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>